### ISSUE TITLE
Possible timing issues when restarting the node after updating the configuration files

### ISSUE THREAD

**Issue by jesus-alastria** [alastria/monitor#5]
https://github.com/alastria/monitor/blob/09e33ebc9fd00ed31d4d0910ed8129611f3c8a9f/lib/node.go#L139-L145
There is an arbitrary sleep time of 1 second between the call to Stop() and Start(). There may be timing issues causing errors on the Start() call if the process has not yet died.
Additionally, because of issue #3 those errors are not detected and are not reported to the caller.

**Comment by adlrocha** [comment]
@jesus-alastria, this random sleep time was for development purposes. We will fix this issue. But again, the problem with #3 needs further analysis.
